### ISSUE TITLE
Hard requiring the absolute latest OBS is annoying

### ISSUE THREAD

**Issue by ghost** [dnaka91/obws#15]
Chasing the latest version for an application is great! I absolutely support updating as much as possible. That said, for a variety of reasons (e.g. Unix vendors not keeping up with packaging), *requiring* the latest version makes working with this crate difficult. I understand that new versions of OBS introduce new websockets APIs, and making them available is a priority for this crate. This is an entirely reasonable thing to do! But I think a more graceful system which only provides those features the running OBS supports would be more friendly to the end user. Are there any websockets APIs introduced in version 27?

**Comment by dnaka91** [comment]
The reason for this strict version requirement is actually not OBS but **obs-websocket**.

The OBS releases are usually reather unexciting from an API perspective and mostly add new features but don't introduce breaking changes, although that can happen from time to time.

But obs-websocket is another challenge. It doesn't properly follow semantic versioning so that even the latest upgrade from `4.9.0` to `4.9.1` introduced breaking changes in the API although it was just a patch release. Besides that it's very strict on the required OBS version. I'm in the Discord server of obs-websocket and there are often questions about obs-websocket not running or OBS directly crashing at startup and most of these issues are due to version mismatches of OBS and the plugin.

Now with this client lib we have 3 components whose versions have to match to work properly. To avoid common issues like they happen in obs-websocket, I added these version checks. Just one wrong version and you're open to a whole bunch of issues and debugging.

Since obs-websocket `4.9.0` the latest OBS 27 is required and the difference between `4.8.0` and `4.9.0` is rather big. That makes it hard to support both API versions at the same time. Also, I didn't think about a good way to support both at the same time and make this crate's API ergonomic about it too.

I think with the upcoming `5.0.0` of obs-websocket things will improve quite a bit. There will be a new `rpcVersion` that is used in the negotiation between a client lib and the plugin and can help determine breaking changes better. I just hope they uphold their promise on upping that version on breaking changes this time.

**Comment by dnaka91** [comment]
There's no reply since about a year now, so I'll close this.

As explained before, it's not all because the `obs-websocket` version is closely bound to the OBS release. Fortunately it'll be bundled with future releases of OBS so that's a neat improvement. But still, as we always target the latest obs-websocket, we'll require a rather recent OBS version.

Maybe this will be changed in the future, but I don't see a nice path for supporting multiple versions at the same time.
