### ISSUE TITLE
Method to get whether recording or streaming is paused?

### ISSUE THREAD

**Issue by bradfordcp** [dnaka91/obws#2]
I've been looking for a way to determine if the recording or stream is currently paused. The methods to pause and unpause these functions will perform the action or return an error. It would be helpful to query whether we are currently paused so the appropriate method may be called (or ignored).

Does this feature exist in the OBS Websocket API?

**Comment by dnaka91** [comment]
Hey there, unfortunately that feature doesn't exist yet.

I already saw some pausing related changes in the dev version of the `obs-websocket` API docs so it's very likely to be included in the next release.

Until they make a new release I can't do much about that, sorry 😐.

**Comment by dnaka91** [comment]
@bradfordcp Sorry, my answer was a little short as I was just about to go to bed. As it turns out, there are already some ways to detect pausing but it's maybe a bit inconvenient.

Current and upcoming release only have a pausing feature for **recording** though, not for **streaming** and I think there is actually no pausing for streaming in OBS, but I'm not 100% sure.

Here are some more details regarding the current version and the upcoming release.

### Current 4.8.0

Currently you can only find out whether streaming/recording is **started** or **stopped** by the [GetStreamingStatus](https://github.com/Palakis/obs-websocket/blob/4.8.0/docs/generated/protocol.md#getstreamingstatus) command, but not get any information about **pausing**.

However, you can listen for pausing events, specifically [RecordingPaused](https://github.com/Palakis/obs-websocket/blob/4.8.0/docs/generated/protocol.md#recordingpaused) and [RecordingResumed](https://github.com/Palakis/obs-websocket/blob/4.8.0/docs/generated/protocol.md#recordingresumed).

### Dev version

The upcoming release has added the pausing information to the command responses. There is a new [GetRecordingStatus](https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#getrecordingstatus) command to get recording details and the [GetStreamingStatus](https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#getstreamingstatus) was extended to include recording pausing information.

**Comment by dnaka91** [comment]
Since version 4.9.0 of obs-websocket and 0.5.0 obws you can get the pause status with the previously mentioned `GetStreamingStatus` and `GetRecordingStatus` requests. I'll close this now as there's not been any response in a while.
