### ISSUE TITLE
Add Serialize to Event structs

### ISSUE THREAD

**Issue by izzy** [dnaka91/obws#27]
I'm currently trying to use obws with serde_json but there's the Serialize derive missing on some of the structs to easily use it with `json!()` etc.. Preliminary tests just adding the derive seemed to be fine but I'm not 100% sure if there's anything else needed. If there's some contribution guidelines I'd be happy to implement it myself. :)

**Comment by dnaka91** [comment]
Thanks for the issue @izzy. You're right, most of the structs currently have only the bare minimum of traits implemented. For example, you'll notice that other traits like `Hash` might be missing too, making it difficult to use them as keys in hash maps.

That is, because so far, I only implemented what was strictly needed for the communication with `obs-websocket` itself. I completely agree that it'd be nice to have some extra traits added, making the structs more usable (especially response types, I guess).

I'll go through all the structs and make sure they have common derives on them (where possible), and add the `Serialize` where it's missing (as well as the other way around for `Deserialize`).

**Comment by dnaka91** [comment]
Published a new version just now, that adds `Serialize` and several other common traits to the responses and the events.

I'll close the issue with that, but feel free to re-open it, in case something is missing 🙇‍♂️
