### ISSUE TITLE
Serde not properly serializing the EventSubscription bitflags

### ISSUE THREAD

**Issue by 715209** [dnaka91/obws#32]
Hi! I seem to have encountered an issue when using `reidentify`.

Digging in to the code it seems to be an issue where Serde is not calling the bits() function, which instead just changes it to send the struct names.

![image](https://github.com/dnaka91/obws/assets/5977687/cf29f329-3602-48dc-803d-66de62c6fe4d)

So changing this to use the bits() function, gives me the expected results.

![image](https://github.com/dnaka91/obws/assets/5977687/8a04883c-f606-4955-8452-2c14a7dbce9c)

![image](https://github.com/dnaka91/obws/assets/5977687/5d8495ac-0f38-48b6-bf05-e54619d48ff2)

**Comment by dnaka91** [comment]
Thank you for the bug report.

I honestly have never used the `reidentify` function so far, and didn't even create an integration test for it. I wonder whether it was always broken or slipped in with the `bitflags` version update.

When investigating, I found out that other values weren't always serialized as number as well. Some were annotated with a custom serialization function and some weren't, even though they should all be serialized as number consistently.

I just now created a bugfix release which fixes this, so that all bitflag values are always encoded as number.

Could you check with the new version (`0.11.2`) again and close the issue if it works?

**Comment by 715209** [comment]
Thank you for the quick fix!
I have always used `reidentify` so it did work fine before, I guess it broke with the `bitflags` version update.

**Comment by 715209** [comment]
Just confirmed that it's working 👍
