### ISSUE TITLE
Please unpin serde version

### ISSUE THREAD

**Issue by KisaragiEffective** [dnaka91/obws#33]
Please unpin serde version, the specifier is conflicting with ours.
https://github.com/dnaka91/obws/blob/9ccc1b2a1f68c8b8ba1b5ff5697c5af4277b6886/Cargo.toml#L26

**Comment by yanorei32** [comment]
I think, can be made relaxed version-pinning for the application developer.

I faced a problem with the application-level version pinning.
https://github.com/yanorei32/obs-spotify-bridge/pull/118#issuecomment-1684860319

**Comment by yanorei32** [comment]
Thanks for responding. I've understood the situation.

but I have a question.
Why this project pins dependency versions?
I think, many libraries are not pinned a version for compatibility between are libraries. (I'm not a expert.)
If some features is required, it can be write like a '^0.1.10'.

**Comment by dnaka91** [comment]
The case of pinning `serde` is really rare. Usually I never pin any dependency to a specific version. If you read through the issue linked above, you can see that serde started to ship a pre-compiled version of the proc macro, that could not be fully reproduced and verified.

Normally proc macros are built from source every time and due to the security implications the pre-compiled version presents, many crate authors started pinning to the version that didn't ship it yet (like the `time` crate for example).

In the meantime, the issue has been resolved, and the author removed the pre-compiled binary again with `1.0.185` so that the pin could be removed again.
