### ISSUE TITLE
ERROR obws::client: failed handling message error=UnexpectedMessage(Event)

### ISSUE THREAD

**Issue by davehorner** [dnaka91/obws#34]
When I run iter_scenes I get a repeating error message.
```
cargo run --example iter_scenes
    Finished dev [unoptimized + debuginfo] target(s) in 0.27s
     Running `target\debug\examples\iter_scenes.exe`
2023-09-02T19:25:15.832848Z DEBUG obws::client::connection: identified against obs-websocket rpc_version=1
2023-09-02T19:25:15.839105Z ERROR obws::client: failed handling message error=UnexpectedMessage(Event)
2023-09-02T19:25:16.164942Z ERROR obws::client: failed handling message error=UnexpectedMessage(Event)
2023-09-02T19:25:16.166915Z ERROR obws::client: failed handling message error=UnexpectedMessage(Event)
```

```
Version {
    obs_version: Version {
        major: 29,
        minor: 1,
        patch: 3,
    },
    obs_web_socket_version: Version {
        major: 5,
        minor: 2,
        patch: 3,
    },
```

The other sample events and simple are working; 
The screenshot example also gave me the same UnexpectedMessage(Event) after creating the 'OBWS-TEST-Scene' required.
```
2023-09-02T19:32:14.431542Z ERROR obws::client: failed handling message error=UnexpectedMessage(Event
```

simple knows how it return the list of scenes.
```
[
    Scene {
        name: "Scene 4",
        index: 0,
    },
    Scene {
        name: "Scene 3",
        index: 1,
    },
    Scene {
        name: "Scene 2",
        index: 2,
    },
    Scene {
        name: "Scene",
        index: 3,
    },
]
```

**Comment by dnaka91** [comment]
Thank you for the bug report!

This error is nothing to worry about, but after a bit of testing, I figured out the issue. It didn't happen before, so I guess they changed a few things on the side of `obs-websocket` or it's because I usually run the examples with all features enabled and simply didn't notice.

The error happens because I didn't catch the case that an event is being received while the `events` feature is **disabled**. 

In addition, the `Client::connect` function does use the default for event subscriptions in all cases, which means it listens to all events except high velocity events. Doesn't really make sense to listen to any events if the feature isn't enabled in the crate.

So I'll make the following changes:
- Handle the case of receiving events when the feature flag isn't enabled, which will effectively downgrade the error to a trace log.
- Changed the defaults in `Client::connect` so it'll tell obs-websocket to not send any events if the feature flag isn't enabled.

**Comment by dnaka91** [comment]
I published a new release now, which should resolve the wrong error logs. Please re-open the issue if the problem still happens :bowing_man:

**Comment by davehorner** [comment]
Following up; I tested and the changes have resolved the issues with all the samples.  Thank you for resolving so quickly!

Looking at the api, I just want to add a new sample to the repo that adds a scene given a url.  it looks like it would be simple using iter_scenes.rs as a base.

```
    let client = Client::connect("localhost", 4455, env::var("OBS_PASSWORD").ok()).await?;
    client.scene_items().create(CreateSceneItem{scene:"OBWS-TEST-Scene",source:"", enabled: Some(true) }).await?;
```
```
2023-09-04T04:54:27.704448Z DEBUG obws::client::connection: identified against obs-websocket rpc_version=1
Error: API error: ResourceNotFound
```

**Comment by dnaka91** [comment]
I'm always open to extending the examples. It's probably out of scope for this issue, but anyway...

To create a new scene item through obs-websocket, you actually don't create a scene item but a new input instead. Any input is automatically a scene item and a scene item can be pretty much anything like an input, another scene, even transitions.

Let's consider we already have two scenes A and B and we want to add some color. Then we can create a new input in scene A as follows:

```rust
client
    .inputs()
    .create(inputs::Create {
        scene: "A",
        input: "green",
        kind: "color_source_v3",
        settings: Some(serde_json::json! {{
            "color": 0xff00ff00_u32,
        }}),
        enabled: None,
    })
    .await?;
```

This is a new input named `green`, added to scene `A` and the color set to green in ABGR (alpha, blue, green and red) order. OBS takes colors in reverse order (instead of the typical RGBA) in general.

Then, the API you were using, can be used to add the input as scene item to another scene. In our example to scene B:

```rust
client
    .scene_items()
    .create(CreateSceneItem {
        scene: "B",
        source: "green",
        enabled: None,
    })
    .await?;
```

As the OBS UI doesn't tell us the exact naming for inputs and their settings, you can use the following to figure it out:

```rust
// get all supported input kinds
println!("{:#?}", client.inputs().list_kinds(false).await?);
// get the settings for a specific kind
println!("{:#?}", client.inputs().default_settings::<serde_json::Value>("color_source_v3").await?);
```

Note that the default settings might not always be accurate, as it's up to each input source to report the default settings. And as they can come from plugins, they might not all be setup correctly to give you the full range of settings. In fact, even some built-in inputs don't report all their settings.

I personally go as far as checking the source for all available settings of an input if needed. An alternative is to create the input in the UI, change every setting in the UI to something non-default and query the settings from the API (as the API omits any default values when querying the current settings of the source).
